name: Vault CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
           version: nightly-b76c57e

      - name: Run Foundry tests
        run: |
          forge install
          forge build
          forge test --gas-report